# roles/podman_install/vars/main.yml
# ==================================
#
# Copying
# -------
#
# Copyright (c) 2023 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
podman_install_service_name: "podman.socket"

podman_install_redhat:
  - "podman"

podman_install_redhat_rootless:
  - "shadow-utils-subid"
  - "passt"

podman_install_family:
  redhat: "{{ podman_install_redhat | union(podman_install_redhat_rootless) }}"

podman_install_package: >-
  {{
    podman_install_family | universe.common.get(
      ansible_facts.distribution | lower,
      ansible_facts.os_family | lower
    )
  }}
