# roles/podman_install/defaults/main.yml
# ======================================
#
# Copying
# -------
#
# Copyright (c) 2023 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
podman_install_enable_system_service: false
podman_install_enable_user_service: false

podman_install_create_user: false
podman_install_user_name: "podman"
podman_install_user_group: "{{ podman_install_user_group }}"
podman_install_user_home: >-
  {{ dirs_sharedstatedir }}/{{ podman_install_user_name }}
podman_install_user_subid_start: 1000000
podman_install_user_subid_count: 65535
